export const currencies = [
    "Afghan afghani (AFN)",
    "Albanian lek (ALL)",
    "Algerian dinar (DZD)",
    "Andorran euro (EUR)",
    "Angolan kwanza (AOA)",
    "Argentine peso (ARS)",
    "Armenian dram (AMD)",
    "Australian dollar (AUD)",
    "Austrian euro (EUR)",
    "Azerbaijani manat (AZN)",
    "Bahamian dollar (BSD)",
    "Bahraini dinar (BHD)",
    "Bangladeshi taka (BDT)",
    "Barbadian dollar (BBD)",
    "Belarusian ruble (BYN)",
    "Belgian euro (EUR)",
    "Belize dollar (BZD)",
    "Beninese franc (XOF)",
    "Bhutanese ngultrum (BTN)",
    "Bolivian boliviano (BOB)",
    "Bosnian convertible mark (BAM)",
    "Botswana pula (BWP)",
    "Brazilian real (BRL)",
    "British pound sterling (GBP)",
    "Brunei dollar (BND)",
    "Bulgarian lev (BGN)",
    "Burundian franc (BIF)",
    "Cambodian riel (KHR)",
    "Cameroonian franc (XAF)",
    "Canadian dollar (CAD)",
    "Cape Verdean escudo (CVE)",
    "Central African CFA franc (XAF)",
    "Chadian franc (XAF)",
    "Chilean peso (CLP)",
    "Chinese yuan (CNY)",
    "Colombian peso (COP)",
    "Comorian franc (KMF)",
    "Congolese franc (CDF)",
    "Costa Rican colón (CRC)",
    "Croatian kuna (HRK)",
    "Cuban peso (CUP)",
    "Czech koruna (CZK)",
    "Danish krone (DKK)",
    "Djiboutian franc (DJF)",
    "Dominican peso (DOP)",
    "East Caribbean dollar (XCD)",
    "Egyptian pound (EGP)",
    "Equatorial Guinean franc (XAF)",
    "Eritrean nakfa (ERN)",
    "Estonian euro (EUR)",
    "Ethiopian birr (ETB)",
    "Euro (EUR)",
    "Fijian dollar (FJD)",
    "Finnish euro (EUR)",
    "French euro (EUR)",
    "Gabonese franc (XAF)",
    "Gambian dalasi (GMD)",
    "Georgian lari (GEL)",
    "German euro (EUR)",
    "Ghanaian cedi (GHS)",
    "Gibraltar pound (GIP)",
    "Greek euro (EUR)",
    "Guatemalan quetzal (GTQ)",
    "Guinean franc (GNF)",
    "Guyanese dollar (GYD)",
    "Haitian gourde (HTG)",
    "Honduran lempira (HNL)",
    "Hong Kong dollar (HKD)",
    "Hungarian forint (HUF)",
    "Icelandic króna (ISK)",
    "Indian rupee (INR)",
    "Indonesian rupiah (IDR)",
    "Iranian rial (IRR)",
    "Iraqi dinar (IQD)",
    "Irish euro (EUR)",
    "Israeli new shekel (ILS)",
    "Italian euro (EUR)",
    "Jamaican dollar (JMD)",
    "Japanese yen (JPY)",
    "Jordanian dinar (JOD)",
    "Kazakhstani tenge (KZT)",
    "Kenyan shilling (KES)",
    "Kuwaiti dinar (KWD)",
    "Kyrgyzstani som (KGS)",
    "Laotian kip (LAK)",
    "Latvian euro (EUR)",
    "Lebanese pound (LBP)",
    "Lesotho loti (LSL)",
    "Liberian dollar (LRD)",
    "Libyan dinar (LYD)",
    "Lithuanian euro (EUR)",
    "Macanese pataca (MOP)",
    "Macedonian denar (MKD)",
    "Malagasy ariary (MGA)",
    "Malawian kwacha (MWK)",
    "Malaysian ringgit (MYR)",
    "Maldivian rufiyaa (MVR)",
    "Mauritanian ouguiya (MRU)",
    "Mauritian rupee (MUR)",
    "Mexican peso (MXN)",
    "Moldovan leu (MDL)",
    "Mongolian tögrög (MNT)",
    "Moroccan dirham (MAD)",
    "Mozambican metical (MZN)",
    "Burmese kyat (MMK)",
    "Namibian dollar (NAD)",
    "Nepalese rupee (NPR)",
    "Netherlands Antillean guilder (ANG)",
    "New Zealand dollar (NZD)",
    "Nicaraguan córdoba (NIO)",
    "Nigerian naira (NGN)",
    "North Korean won (KPW)",
    "Norwegian krone (NOK)",
    "Omani rial (OMR)",
    "Pakistani rupee (PKR)",
    "Panamanian balboa (PAB)",
    "Papua New Guinean kina (PGK)",
    "Paraguayan guaraní (PYG)",
    "Peruvian sol (PEN)",
    "Philippine peso (PHP)",
    "Polish złoty (PLN)",
    "Qatari riyal (QAR)",
    "Romanian leu (RON)",
    "Russian ruble (RUB)",
    "Rwandan franc (RWF)",
    "Saint Helena pound (SHP)",
    "Salvadoran colón (SVC)",
    "Samoan tālā (WST)",
    "São Tomé and Príncipe dobra (STN)",
    "Saudi riyal (SAR)",
    "Serbian dinar (RSD)",
    "Seychellois rupee (SCR)",
    "Sierra Leonean leone (SLL)",
    "Singapore dollar (SGD)",
    "Slovak euro (EUR)",
    "Slovenian euro (EUR)",
    "Solomon Islands dollar (SBD)",
    "Somali shilling (SOS)",
    "South African rand (ZAR)",
    "South Korean won (KRW)",
    "South Sudanese pound (SSP)",
    "Spanish euro (EUR)",
    "Sri Lankan rupee (LKR)",
    "Sudanese pound (SDG)",
    "Surinamese dollar (SRD)",
    "Swazi lilangeni (SZL)",
    "Swedish krona (SEK)",
    "Swiss franc (CHF)",
    "Syrian pound (SYP)",
    "Taiwanese dollar (TWD)",
    "Tajikistani somoni (TJS)",
    "Tanzanian shilling (TZS)",
    "Thai baht (THB)",
]
